// <auto-generated />
using System;
using EmployeeEvaluation.DataAccess.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeEvaluation.Migrations
{
    [DbContext(typeof(FormTemplateDbContext))]
    [Migration("20220903185104_FormTemplateMigration")]
    partial class FormTemplateMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EmployeeEvaluation.DataAccess.Model.FormTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FormTemplates");
                });

            modelBuilder.Entity("EmployeeEvaluation.DataAccess.Model.FormTemplateCriteria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FormTemplateSectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FormTemplateSectionId");

                    b.ToTable("FormTemplateCriteria");
                });

            modelBuilder.Entity("EmployeeEvaluation.DataAccess.Model.FormTemplateSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FormTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FormTemplateId");

                    b.ToTable("FormTemplateSections");
                });

            modelBuilder.Entity("EmployeeEvaluation.DataAccess.Model.FormTemplateCriteria", b =>
                {
                    b.HasOne("EmployeeEvaluation.DataAccess.Model.FormTemplateSection", null)
                        .WithMany("TemplateCriteria")
                        .HasForeignKey("FormTemplateSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmployeeEvaluation.DataAccess.Model.FormTemplateSection", b =>
                {
                    b.HasOne("EmployeeEvaluation.DataAccess.Model.FormTemplate", null)
                        .WithMany("TemplateSections")
                        .HasForeignKey("FormTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmployeeEvaluation.DataAccess.Model.FormTemplate", b =>
                {
                    b.Navigation("TemplateSections");
                });

            modelBuilder.Entity("EmployeeEvaluation.DataAccess.Model.FormTemplateSection", b =>
                {
                    b.Navigation("TemplateCriteria");
                });
#pragma warning restore 612, 618
        }
    }
}
